import requests
from credentials import cc_client_id, cc_token

# Constant Contact API.
base_url = 'https://api.constantcontact.com/v2/activities'
endpoint = '/addcontacts?api_key='
url = base_url + endpoint + cc_client_id
headers = {'Authorization': ('Bearer ' + cc_token)}


def create_payload(contacts, list_id):
    '''Creates the JSON payloads sent in the request to the Constant Contact API.

    Arguments:
        contacts = The list of contacts generated by append_contacts().
        list_id = The ID of the list in Constant Contact that the new contacts
        will be uploaded to.

    Returns:
        payload: a JSON formatted dictionary with a list of contacts, the ID of
        the Constant Contact list the contacts will be added to, and the column
        names of the contacts's data.
    '''
    payload = {'import_data': contacts,
               'lists': [list_id],
               'column_names': ['Email Address', 'First Name',
                                'Last Name', 'Home Phone',
                                'Address Line 1', 'Address Line 2',
                                'City', 'State',
                                'Zip/Postal Code']}
    return payload


def add_contacts(payload):
    '''POSTs a JSON payload to the Constant Contact API.

    Arguments:
        payload = The payload returned by create_payload().
    '''
    r = requests.post(url, headers=headers, json=payload)
    print(r.status_code)
    print(r.reason)
    print(r.text)
    print('-------------')
